name: Github CI

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test and coverage
      run: |
        npm install
        npm test
      env:
        CI: true
    - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      with:
        path: "./coverage/lcov.info"
        min_coverage: 80

